<%@ page import="java.util.List" %>
<%@ page import="com.smartdairy.entity.Customer" %>
<%@ page import="com.smartdairy.service.CustomerService" %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Smart Dairy - Customers</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head>
<body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><span class="navbar-brand fw-bold">Smart Dairy — Customer Management</span><a href="CustomerDashboardServlet" class="btn btn-outline-light">Customer Dashboard</a></div></nav>
<div class="container py-4"><% String success=request.getParameter("success"),updated=request.getParameter("updated"),deleted=request.getParameter("deleted"),error=request.getParameter("error"); if("true".equals(success)){%><div class="alert alert-success">Customer added successfully.</div><%} if("true".equals(updated)){%><div class="alert alert-success">Customer updated successfully.</div><%} if("true".equals(deleted)){%><div class="alert alert-success">Customer deleted successfully.</div><%} if(error!=null && !"true".equals(error)){%><div class="alert alert-danger"><%=error%></div><%} else if("true".equals(error)){%><div class="alert alert-danger">Something went wrong. Please try again.</div><%}%>
<div class="card shadow-sm mb-4"><div class="card-body"><h4 class="card-title">Add Customer / Buyer</h4><form action="CustomerServlet" method="post" class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" minlength="2" required></div><div class="col-md-6"><label class="form-label">Mobile</label><input class="form-control" name="mobile" pattern="[0-9]{10}" maxlength="10" required></div><div class="col-md-6"><label class="form-label">Address</label><input class="form-control" name="address"></div><div class="col-md-3"><label class="form-label">Customer Type</label><select class="form-select" name="customer_type"><option>RETAIL</option><option>WHOLESALER</option><option>HOTEL</option><option>RESTAURANT</option><option>OTHER</option></select></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option>ACTIVE</option><option>INACTIVE</option></select></div><div class="col-12"><button class="btn btn-success">Add Customer</button></div></form></div></div>
<div class="card shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2"><h4 class="mb-0">Customer List</h4><form class="d-flex" method="get" action="customer.jsp"><input class="form-control me-2" name="search" value="<%=request.getParameter("search")==null?"":request.getParameter("search")%>" placeholder="Search name, mobile, address..."><button class="btn btn-primary">Search</button></form></div><div class="table-responsive mt-3"><table class="table table-hover align-middle"><thead class="table-dark"><tr><th>ID</th><th>Name</th><th>Mobile</th><th>Address</th><th>Type</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<% try { CustomerService service=new CustomerService(); List<Customer> customers=service.search(request.getParameter("search")); for(Customer c:customers){ %><tr><td><%=c.getId()%></td><td><%=c.getName()%></td><td><%=c.getMobile()%></td><td><%=c.getAddress()==null?"":c.getAddress()%></td><td><span class="badge text-bg-secondary"><%=c.getCustomerType()%></span></td><td><span class="badge <%= "ACTIVE".equals(c.getStatus())?"text-bg-success":"text-bg-warning" %>"><%=c.getStatus()%></span></td><td><a class="btn btn-sm btn-warning" href="customer_edit.jsp?id=<%=c.getId()%>">Edit</a> <a class="btn btn-sm btn-danger" href="CustomerDeleteServlet?id=<%=c.getId()%>" onclick="return confirm('Delete this customer?')">Delete</a></td></tr><% }} catch(Exception e){ %><tr><td colspan="7" class="text-danger">Unable to load customers.</td></tr><% } %></tbody></table></div></div></div></div></body></html>
