<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.util.List,com.smartdairy.entity.Product,com.smartdairy.entity.InventoryTransaction" %>
<% List<Product> products=(List<Product>)request.getAttribute("products"); List<InventoryTransaction> transactions=(List<InventoryTransaction>)request.getAttribute("transactions"); %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Inventory - Smart Dairy</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head>
<body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container"><span class="navbar-brand fw-bold">Smart Dairy</span><span class="text-white">Inventory Management</span></div></nav><div class="container py-4">
<% if("true".equals(request.getParameter("success"))){%><div class="alert alert-success">Inventory transaction saved and product stock updated.</div><%}%>
<% if(request.getParameter("error")!=null){%><div class="alert alert-danger">Transaction failed: <%=request.getParameter("error")%></div><%}%>
<div class="row g-4"><div class="col-lg-4"><div class="card shadow-sm"><div class="card-body"><h5>Stock Transaction</h5><form action="InventoryServlet" method="post" class="row g-3">
<div class="col-12"><label class="form-label">Product</label><select name="product_id" class="form-select" required><option value="">Select product</option><% if(products!=null) for(Product p:products){%><option value="<%=p.getId()%>"><%=p.getProductName()%> (Stock: <%=p.getStock()%>)</option><%}%></select></div>
<div class="col-md-6"><label class="form-label">Type</label><select name="transaction_type" class="form-select" required><option value="STOCK IN">STOCK IN</option><option value="STOCK OUT">STOCK OUT</option></select></div>
<div class="col-md-6"><label class="form-label">Quantity</label><input name="quantity" type="number" step="0.01" min="0.01" class="form-control" required></div>
<div class="col-md-6"><label class="form-label">Reference Type</label><select name="reference_type" class="form-select"><option value="MANUAL">MANUAL</option><option value="PURCHASE">PURCHASE</option><option value="SALE">SALE</option><option value="ORDER">ORDER</option></select></div>
<div class="col-md-6"><label class="form-label">Reference ID</label><input name="reference_id" type="number" min="1" class="form-control"></div>
<div class="col-12"><label class="form-label">Transaction Date</label><input name="transaction_date" type="datetime-local" class="form-control"></div>
<div class="col-12"><label class="form-label">Remarks</label><textarea name="remarks" class="form-control" rows="3"></textarea></div>
<div class="col-12"><button class="btn btn-dark w-100">Save Transaction</button></div></form></div></div></div>
<div class="col-lg-8"><div class="card shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Inventory History</h5><input id="search" class="form-control w-50" placeholder="Search..." onkeyup="filterTable()"></div><div class="table-responsive"><table class="table table-hover" id="inventoryTable"><thead class="table-dark"><tr><th>ID</th><th>Product</th><th>Type</th><th>Qty</th><th>Reference</th><th>Date</th><th>Remarks</th></tr></thead><tbody>
<% if(transactions!=null) for(InventoryTransaction t:transactions){%><tr><td><%=t.getId()%></td><td><%=t.getProductName()%></td><td><span class="badge <%= "STOCK IN".equals(t.getTransactionType())?"bg-success":"bg-danger"%>"><%=t.getTransactionType()%></span></td><td><%=t.getQuantity()%></td><td><%=t.getReferenceType()%><%=t.getReferenceId()!=null?" #"+t.getReferenceId():""%></td><td><%=t.getTransactionDate()%></td><td><%=t.getRemarks()==null?"":t.getRemarks()%></td></tr><%}%>
</tbody></table></div></div></div></div></div></div><script>function filterTable(){let q=document.getElementById('search').value.toLowerCase();document.querySelectorAll('#inventoryTable tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?'':'none');}</script></body></html>
