package com.smartdairy.repository;
import com.smartdairy.entity.Supplier; import com.smartdairy.util.DBConnection; import java.sql.*; import java.util.*;
public class SupplierRepository {
 public int save(Supplier s)throws Exception{String q="INSERT INTO suppliers(name,mobile,address,animal_type,bank_details,status) VALUES(?,?,?,?,?,?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setString(1,s.getName());p.setString(2,s.getMobile());p.setString(3,s.getAddress());p.setString(4,s.getAnimalType());p.setString(5,s.getBankDetails());p.setString(6,s.getStatus());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())s.setId(r.getInt(1));}}return s.getId();}
 public boolean update(Supplier s)throws Exception{String q="UPDATE suppliers SET name=?,mobile=?,address=?,animal_type=?,bank_details=?,status=? WHERE id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,s.getName());p.setString(2,s.getMobile());p.setString(3,s.getAddress());p.setString(4,s.getAnimalType());p.setString(5,s.getBankDetails());p.setString(6,s.getStatus());p.setInt(7,s.getId());return p.executeUpdate()>0;}}
 public boolean delete(int id)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM suppliers WHERE id=?")){p.setInt(1,id);return p.executeUpdate()>0;}}
 public Supplier findById(int id)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM suppliers WHERE id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}}
 public List<Supplier> findAll(String search)throws Exception{String q="SELECT * FROM suppliers WHERE name LIKE ? OR mobile LIKE ? OR animal_type LIKE ? ORDER BY id DESC";List<Supplier> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){String s="%"+(search==null?"":search.trim())+"%";p.setString(1,s);p.setString(2,s);p.setString(3,s);try(ResultSet r=p.executeQuery()){while(r.next())out.add(map(r));}}return out;}
 private Supplier map(ResultSet r)throws SQLException{Supplier s=new Supplier();s.setId(r.getInt("id"));s.setName(r.getString("name"));s.setMobile(r.getString("mobile"));s.setAddress(r.getString("address"));s.setAnimalType(r.getString("animal_type"));s.setBankDetails(r.getString("bank_details"));s.setStatus(r.getString("status"));return s;}
}
