package com.smartdairy.repository;
import com.smartdairy.entity.Delivery; import com.smartdairy.util.DBConnection; import java.sql.*; import java.util.*;
public class DeliveryRepository {
 public void save(Delivery d)throws Exception{String q="INSERT INTO deliveries(order_id,delivery_person,mobile,vehicle_number,delivery_date,route,status,remarks) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){set(p,d);p.executeUpdate();}}
 public void update(Delivery d)throws Exception{String q="UPDATE deliveries SET order_id=?,delivery_person=?,mobile=?,vehicle_number=?,delivery_date=?,route=?,status=?,remarks=? WHERE id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){set(p,d);p.setInt(9,d.getId());p.executeUpdate();}}
 private void set(PreparedStatement p,Delivery d)throws Exception{p.setInt(1,d.getOrderId());p.setString(2,d.getDeliveryPerson());p.setString(3,d.getMobile());p.setString(4,d.getVehicleNumber());p.setDate(5,d.getDeliveryDate());p.setString(6,d.getRoute());p.setString(7,d.getStatus());p.setString(8,d.getRemarks());}
 public void delete(int id)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM deliveries WHERE id=?")){p.setInt(1,id);p.executeUpdate();}}
 public List<Delivery> findAll()throws Exception{List<Delivery>a=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM deliveries ORDER BY delivery_date DESC,id DESC");ResultSet r=p.executeQuery()){while(r.next()){Delivery d=new Delivery();d.setId(r.getInt("id"));d.setOrderId(r.getInt("order_id"));d.setDeliveryPerson(r.getString("delivery_person"));d.setMobile(r.getString("mobile"));d.setVehicleNumber(r.getString("vehicle_number"));d.setDeliveryDate(r.getDate("delivery_date"));d.setRoute(r.getString("route"));d.setStatus(r.getString("status"));d.setRemarks(r.getString("remarks"));a.add(d);}}return a;}
}
